<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="style.css">
<title>Login</title>
</head>
<body>
	<header>
		<h1>Welcome to Malaysian Software Developer Portal</h1>
	</header>
	
	<div class="hero">
		<h2>Login</h2>
		<form action="login" method="post">
			<label for="email">Email</label><br>
			<input type="text" id="email" name="email" placeholder="Enter your email" required /><br>
			
			<label for="password">Password</label><br>
			<input type="password" id="password" name="password" placeholder="Enter your password" required /><br><br>
			
			<button style="margin-top: 1em;" type="submit">Login</button>

			<c:if test="${not empty errorMessage}">
				<p style="color: red;">${errorMessage} Forgot password? Click <a href="/jsp-project/forgot">here</a></p>
			</c:if>
		</form>
	</div>
	
	
	<footer style="margin-top:2em;"><a href="/jsp-project">MSDF</a> &copy; 2024. Made with &#10084; in Penang. All images generated by DALL-E.</footer>
</body>
</html> 