<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Register</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
	<header>
        <h1>Welcome to Malaysian Software Developer Portal</h1>
    </header>
	<section class="hero">
        <h2>Register</h2>
        <form action="register" method="post">
            <label for="firstname">Firstname:</label><br>
            <input type="text" id="firstname" name="firstname" required><br>
            
            <label for="lastname">Lastname:</label><br>
            <input type="text" id="lastname" name="lastname" required><br>
            
            <label for="email">Email:</label><br>
            <input type="email" id="email" name="email" required><br>
            
            <label for="password">Password:</label><br>
            <input type="password" id="password" name="password" required><br>
            
            <label for="cpassword">Confirm Password:</label><br>
            <input type="password" id="cpassword" name="cpassword" required><br>
            
            <label for="company">Company:</label><br>
            <input type="text" id="company" name="company" required><br><br>
            
            <label for="city">City:</label><br>
            <input type="text" id="city" name="city" required><br><br>
            
            <label for="country">Country:</label><br>
            <input type="text" id="country" name="country" required><br><br>
            
            <button type="submit">Register</button>
            
            <c:if test="${not empty errorMessage}">
			<div class="form-group mt-2" style="margin-top:2em;">
				<p style="color: red;">${errorMessage} Login? Click <a href="/jsp-project/login">here</a></p>
			</div>
			</c:if>
        </form>
    </section>
	
	<footer style="margin-top:2em;"><a href="/jsp-project">MSDF</a> &copy; 2024. Made with &#10084; in Penang. All images generated by DALL-E.</footer>
</body>
</html>