<%@ page language="java" contentType="text/html; charset=US-ASCII"
    pageEncoding="US-ASCII"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="US-ASCII">
<title>User Profile</title>
</head>
<body>
	<h2>Update Profile</h2>
	<c:if test="${not empty user}">
	<form action="user" method="post">
		<input type="hidden" id="id" name="id" value="${user.id}" /><br>
		
		<label for="firstname">Firstname</label>
		<input type="text" id="firstname" name="firstname" value="${user.firstname}" /><br><br>
		
		<label for="lastname">Lastname</label>
		<input type="text" id="lastname" name="lastname" value="${user.lastname}" /><br><br>
		
		<label for="company">Company</label>
		<input type="text" id="company" name="company" value="${user.company}" /><br><br>
		
		<label for="city">City</label>
		<input type="text" id="city" name="city" value="${user.city}" /><br><br>
		
		<label for="country">Country</label>
		<input type="text" id="country" name="country" value="${user.country}" /><br><br>
		
		<a href="/jsp-project/dashboard">Cancel</a>
		<button type="submit">Update</button>
	</form>
	</c:if>
	
	<footer style="margin-top:2em;"><a href="/jsp-project">MSDF</a> &copy; 2024. Made with &#10084; in Penang. All images generated by DALL-E.</footer>
</body>
</html>